# This is to run the Dockerfile.

version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
